refactor(DropdownItem): make wrapping of children with anchor tag optional
daisyui/react-daisyui pull request #386
Opened 2023-07-18 09:09 UTC by kodjunkie

I believe this solves #144 and also, allows the usage of the new updates introduced to daisyUI v3 related to Menu (eg: [Menu with active item](https://daisyui.com/components/menu/#menu-with-active-item)). The default behavior is the case where the `children` is wrapped in an anchor tag so it doesn't cause a breaking change.

2023-07-18 21:16 UTC, benjitrosch requested changes
@kodjunkie I like the idea, thanks for the PR! My one concern is that then the props don't match (the props are currently typed as `React.AnchorHTMLAttributes<HTMLAnchorElement>`) and cannot be passed thru to any effect. If you can solve this issue, I'm happy to approve!

2023-07-20 13:25 UTC, kodjunkie commented
Yes, that's the case for users who want to use the default wrapped anchor tag. If you're passing a full react node as `children` and the anchor tag is unnecessary then, the only required prop is `anchor={false}`.

2023-07-20 14:13 UTC, benjitrosch commented
> Yes, that's the case for users who want to use the default wrapped anchor tag. If you're passing a full react node as `children` and the anchor tag is unnecessary then, the only required prop is `anchor={false}`.

Right but the component's props are still typed as anchor attributes and it will still accept props as if that were the underlying element. Because of this a developer could pass in props but nothing will happen, which would be a misleading developer experience.

You could use something like a Discriminated Union which will only type it as `AnchorHTMLAttributes` if `anchor={false}` and otherwise just pass through children and nothing else.

2023-07-20 15:28 UTC, kodjunkie commented
> > Yes, that's the case for users who want to use the default wrapped anchor tag. If you're passing a full react node as `children` and the anchor tag is unnecessary then, the only required prop is `anchor={false}`.
> 
> Right but the component's props are still typed as anchor attributes and it will still accept props as if that were the underlying element. Because of this a developer could pass in props but nothing will happen, which would be a misleading developer experience.
> 
> You could use something like a Discriminated Union which will only type it as `AnchorHTMLAttributes` if `anchor={false}` and otherwise just pass through children and nothing else.

You're right, I just pushed a fix.

2023-07-21 14:18 UTC, benjitrosch approved these changes
@kodjunkie thanks for making the change, looks good!

2023-07-21 14:19 UTC, merged